# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b03b637c0277a1a48934237d51ff9910e49dd2ed8a6f098a76eeb51478a8aa8b1f0048987a1d91da8ff8461f5214e45247dfcb02e21d13952bbc62c761522bc2

test:
  secret_key_base: a98ba7e0fe144e5958e1768ec25e566d18f4895959d4ccba62c1e5ada766d2bce039ffb8d0bcb4ac8fe59dfb6fe64477cf8485a7f7b9c9e1878b4dbc669f7f0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
